# Generated by Django 3.2 on 2023-05-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_proyecto_nombre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='link_meet',
            field=models.URLField(default=None, max_length=100, null=True, verbose_name='Link de Meet'),
        ),
    ]
